CREATE TABLE IF NOT EXISTS  orders(
"id" SERIAL ,
"user_id" BIGINT REFERENCES users(id) ON DELETE CASCADE,  
"status" boolean DEFAULT FALSE,
"created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY("id")
);
