CREATE TABLE IF NOT EXISTS  products(
"id" SERIAL , 
"name" VARCHAR(150) NOT NULL,  
"price" INT NOT NULL DEFAULT(0) , 
"created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY("id")
);
