CREATE TABLE IF NOT EXISTS  orders_products(
"id" SERIAL , 
"product_id" BIGINT REFERENCES products(id) ON DELETE CASCADE,  
"qty" INT NOT NULL DEFAULT(1) , 
"order_id" BIGINT REFERENCES orders(id) ON DELETE CASCADE,  
"created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY("id")
);
